###
GET http://localhost:3002/credit-cards


###
POST http://localhost:3002/credit-cards
Content-Type: application/json

{
    "name": "Luiz Carlos",
    "number": "0111111111111103"
}

## 1111111111111103

###
GET http://localhost:3002/credit-cards/1111111111111103/invoices